-- Create conversations table for Aura AI
CREATE TABLE IF NOT EXISTS public.conversations_aura (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wallet_address TEXT NOT NULL,
    title TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create messages table for Aura AI
CREATE TABLE IF NOT EXISTS public.messages_aura (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id UUID NOT NULL REFERENCES public.conversations_aura(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'ai', 'system', 'error')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_conversations_aura_wallet ON public.conversations_aura(wallet_address);
CREATE INDEX IF NOT EXISTS idx_messages_aura_conversation ON public.messages_aura(conversation_id);

-- Enable RLS (Row Level Security)
ALTER TABLE public.conversations_aura ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages_aura ENABLE ROW LEVEL SECURITY;

-- Allow service role full access (Since backend uses SUPABASE_SERVICE_ROLE_KEY)
CREATE POLICY "Service Role Full Access Conversations" ON public.conversations_aura
    AS PERMISSIVE FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Service Role Full Access Messages" ON public.messages_aura
    AS PERMISSIVE FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);
